name: 'Dotfiles CI'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # 基本テスト（構文チェック等）
  test:
    name: 基本テスト
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 環境情報を表示
        run: |
          echo "=== CI環境情報 ==="
          echo "Working Directory: $(pwd)"
          echo "Home Directory: $HOME"
          echo "CI: $CI"
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
          ls -la

      - name: 基本テストを実行
        run: make test

  # macOS（Intel）でのテスト
  macos-intel:
    name: macOS Intel テスト
    runs-on: macos-13  # Intel Mac
    needs: test
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: プラットフォーム情報を表示
        run: |
          echo "=== システム情報 ==="
          uname -a
          echo "=== アーキテクチャ ==="
          uname -m
          echo "=== macOSバージョン ==="
          sw_vers

      - name: 基本テストを実行
        run: make test

      - name: dotfilesセットアップ（init + link のみ）
        run: |
          # ホームディレクトリにdotfilesディレクトリを作成
          cp -r . $HOME/dotfiles
          cd $HOME/dotfiles
          make init
          make link

      - name: 設定検証を実行
        run: |
          cd $HOME/dotfiles
          make verify
        continue-on-error: true

  # macOS（ARM）でのテスト
  macos-arm:
    name: macOS ARM テスト
    runs-on: macos-latest  # ARM Mac
    needs: test
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: プラットフォーム情報を表示
        run: |
          echo "=== システム情報 ==="
          uname -a
          echo "=== アーキテクチャ ==="
          uname -m
          echo "=== macOSバージョン ==="
          sw_vers

      - name: 基本テストを実行
        run: make test

      - name: dotfilesセットアップ（init + link のみ）
        run: |
          # ホームディレクトリにdotfilesディレクトリを作成
          cp -r . $HOME/dotfiles
          cd $HOME/dotfiles
          make init
          make link

      - name: 設定検証を実行
        run: |
          cd $HOME/dotfiles
          make verify
        continue-on-error: true

  # Ubuntu（最新）でのテスト
  ubuntu-latest:
    name: Ubuntu 最新 テスト
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: プラットフォーム情報を表示
        run: |
          echo "=== システム情報 ==="
          uname -a
          echo "=== ディストリビューション ==="
          cat /etc/os-release
          echo "=== アーキテクチャ ==="
          uname -m

      - name: 基本テストを実行
        run: make test

      - name: dotfilesセットアップ（init + link のみ）
        run: |
          # ホームディレクトリにdotfilesディレクトリを作成
          cp -r . $HOME/dotfiles
          cd $HOME/dotfiles
          make init
          make link

      - name: 設定検証を実行
        run: |
          cd $HOME/dotfiles
          make verify
        continue-on-error: true

  # Ubuntu 20.04でのテスト
  ubuntu-20:
    name: Ubuntu 20.04 テスト
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: プラットフォーム情報を表示
        run: |
          echo "=== システム情報 ==="
          uname -a
          echo "=== ディストリビューション ==="
          cat /etc/os-release

      - name: 基本テストを実行
        run: make test

      - name: dotfilesセットアップ（init + link のみ）
        run: |
          # ホームディレクトリにdotfilesディレクトリを作成
          cp -r . $HOME/dotfiles
          cd $HOME/dotfiles
          make init
          make link

      - name: 設定検証を実行
        run: |
          cd $HOME/dotfiles
          make verify
        continue-on-error: true

  # Dockerでのテスト
  docker-test:
    name: Docker テスト
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Docker Composeでテスト実行
        run: |
          docker-compose -f docker-compose.test.yml run --rm ubuntu-22